sistemavendas/sitevendas/loja/urls.py
from django.urls import path
from . import views

app_name = 'loja'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:product_id>/<int:order_id>/add', views.AddView.as_view(), name="add_item"),
    path('<int:product_id>/<int:order_id>/remove', views.RemoveView.as_view(), name='remove_item'),
    path('<int:perfil_id>/order', views.OrderView.as_view(), name='list_order')
]

sistemavendas/sitevendas/sitevendas/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('usuario/', include('usuarios.urls')),
    path('', include('loja.urls')),
    path('loja/', include('loja.urls')),
    path('admin/', admin.site.urls),
]

sistemavendas/sitevendas/usuarios/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'usuarios'
urlpatterns = [
    path('registrar/', views.RegisterView.as_view(), name='registrar'),
    path('login/',  auth_views.LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

sistemavendas/sitevendas/loja/models.py
from django.db import models
from usuarios.models import Perfil


class Product(models.Model):
    CATEGORY_CHOICES = (
        ('PRC', 'Processadores'),
        ('M.R', 'Memória Ram'),
        ('D.R', 'Disco Rígido/SSD'),
        ('P.V', 'Placa de Vídeo'),
        ('GBT', 'Gabinete'),
        ('P.M', 'Placa Mãe'),
        ('F.T', 'Fonte'),
    )
    name = models.CharField(max_length=200)
    specification = models.CharField(max_length=200)
    price = models.FloatField()
    category = models.CharField(
        max_length = 3,
        choices = CATEGORY_CHOICES,
    )
    
    def __str__(self):
        return self.name

class Stock(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE, primary_key=True)
    total = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str("{}-{}").format(self.product.name, self.total)   

class Order(models.Model):
    STATUS_CHOICES = (
        ('P.A', 'Pedido Aberto'),
        ('P.R', 'Pedido Realizado'),
        ('S.E', 'Separação em Estoque'),
        ('MTG', 'Em montagem'),
        ('R.T', 'Realização de testes'),
    )
    client = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    order_date = models.DateTimeField('data emissão')
    status_order = models.CharField(
        max_length = 3,
        choices = STATUS_CHOICES,
        default = "P.A"
    )

    @staticmethod
    def returnOpenOrder(perfil):
        last_order_open = Order.objects.filter(client=perfil, status_order='P.A')
        if len(last_order_open) == 0:
            current_client = self.request.user.perfil
            current_order = Order(client=current_client, order_date=datetime.now())
            current_order.save()
            return current_order
        else:
            return last_order_open.first

    def __str__(self):
        return str("{}-{}").format(self.client.nome, self.order_date)

class ItemOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.FloatField()
    qtde = models.PositiveIntegerField()

    def total(self):
        return self.price * self.qtde
    
    def __str__(self):
        return str("{}-{}").format(self.product.name, self.qtde)

class Invoice(models.Model):
    PAYMENT_CHOICES = (
        ('DIN', 'Dinheiro'),
        ('CHE', 'Cheque'),
        ('CTC', 'Cartão de Crédito'),
        ('CTD', 'Cartão de Débito'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment_method = models.CharField(
        max_length = 3,
        choices = PAYMENT_CHOICES,
    )
    price = models.FloatField()

    def __str__(self):
        return str("ID{}-{}").format(self.order.id, self.price)

sistemavendas/sitevendas/loja/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.shortcuts import redirect, render
from .models import Product, Order, ItemOrder, Stock
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from datetime import datetime


class IndexView(View):
    template_name = 'loja/loja.html'

    def openOrder(self, perfil):
        last_order_open = Order.objects.filter(client=perfil, status_order='P.A')
        if len(last_order_open) == 0:
            current_client = perfil
            current_order = Order(client=current_client, order_date=datetime.now())
            current_order.save()
            return current_order
        else:
            return last_order_open.first

    def get(self, request):
        list_product = Product.objects.filter()
        context = {'list_product': list_product}
        if(request.user.is_authenticated):
            perfil = request.user.perfil
            opened_order = self.openOrder(perfil)
            last_order_open = Order.objects.filter(client=perfil, status_order='P.A')
            selected_order = ItemOrder.objects.filter(order__in=last_order_open).values_list('product', flat=True)
            context['perfil'] = perfil
            context['order'] = opened_order
            context['itens_order'] = selected_order
        return render(request, self.template_name, context)


class AddView(View):
    template_name = 'loja/add.html'

    def openOrder(self, perfil):
        last_order_open = Order.objects.filter(client=perfil, status_order='P.A')
        if len(last_order_open) == 0:
            current_client = perfil
            current_order = Order(client=current_client, order_date=datetime.now())
            current_order.save()
            return current_order
        else:
            return last_order_open.first

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, product_id, order_id):
        perfil = request.user.perfil
        opened_order = self.openOrder(perfil)
        product = Product.objects.get(pk=product_id)
        stock = Stock.objects.get(product=product)
        context = {
            'product': product,
            'order': opened_order,
            'stock': stock,
            'perfil': perfil
        }
        return render(request, self.template_name, context)

    def post(self, request, product_id, order_id):
        opened_order = Order.objects.get(pk=order_id)
        product = Product.objects.get(pk=product_id)
        newItem = ItemOrder.objects.create(order=opened_order, product=product, 
                                           price=product.price, qtde=1)
        stock = Stock.objects.get(product=product)
        stock.total = stock.total - newItem.qtde
        stock.save()
        newItem.save()
        return redirect('loja:index')
   

class RemoveView(View):
    template_name = 'loja/delete.html'

    def openOrder(self, perfil):
        last_order_open = Order.objects.filter(client=perfil, status_order='P.A')
        if len(last_order_open) == 0:
            current_client = perfil
            current_order = Order(client=current_client, order_date=datetime.now())
            current_order.save()
            return current_order
        else:
            return last_order_open.first
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, product_id, order_id):
        perfil = request.user.perfil
        opened_order = self.openOrder(perfil)
        product = Product.objects.get(pk=product_id)
        context = {
            'product': product,
            'order': opened_order,
            'perfil': perfil
        }
        return render(request, self.template_name, context)

    def post(self, request, product_id, order_id):
        delete_item = ItemOrder.objects.get(order__id=order_id, product__id=product_id)
        product = Product.objects.get(pk=product_id)
        stock = Stock.objects.get(product=product)
        stock.total = stock.total + delete_item.qtde
        stock.save()
        delete_item.delete()
        return redirect('loja:index')
  

class OrderView(View):
    template_name = 'loja/order.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, perfil_id):
        perfil = request.user.perfil
        list_order = Order.objects.filter(client__id = perfil_id)
        context = {
            'perfil': perfil,
            'list_order': list_order
        }
        return render(request, self.template_name, context)
    
    def post(self, request, perfil_id):
        finalize_order = Order.objects.filter(client__id = perfil_id, status_order='P.A').update(status_order='P.R')
        return redirect('loja:index')


@login_required
def finalizeItemOrder(request, pedido_id):
    perfil = request.user.perfil
    return HttpResponse("Finalizando Item %s" % pedido_id)

sistemavendas/sitevendas/loja/templates/loja/add.html
{% extends "loja/base_loja.html" %}
{% block body %}
<div class="main-description">
    {% if stock.total > 0%}
    <h1>Você confirma a adição de {{product.name}} no pedido?</h1>
    {%else%}
    <h1>Sem estoque. Volte mais Tarde.</h1>
    {% endif %}
    <form class="form-signin" action="{% url 'loja:add_item' product_id=product.id order_id=order.id%}" method="post">
        {% csrf_token %}
        {% if stock.total > 0%}
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>
        {%endif%}        
    </form>
    <a href="{%url 'loja:index'%}">Voltar</a>
</div>
{% endblock %}

sistemavendas/sitevendas/loja/templates/loja/base_loja.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>Vendas</title>
        <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "styles/main.css" %}" rel="stylesheet">
    </head>

    <div class="header">
            <ul class="nav nav-pills pull-right">
            {% if perfil %}
                <li><a href="{%url 'usuarios:logout'%}"> Logout </a></li>
                <li><a href="{%url 'loja:list_order' perfil_id=perfil.id%}">  Pedido </a></li>
            {% else %}
                <li><a href="{% url 'usuarios:login' %}"> Login </a></li>
                <li><a href="{% url 'usuarios:registrar' %}"> Registre-se</a></li>
            {% endif %}
            </ul>
    <h3 class="text-muted">Loja Virtual</h3>
    </div>

    <body>
        <div class="container">
            {% block body %}

            {% endblock %} 
        </div>
    </body>
</html>

sistemavendas/sitevendas/loja/templates/loja/delete.html
{% extends "loja/base_loja.html" %}
{% block body %}
<div class="main-description">
    <h1>Você confirma a exclusão de {{product.name}} no pedido?</h1>
    <form class="form-signin" action="{% url 'loja:remove_item' product_id=product.id order_id=order.id%}" method="post">
        {% csrf_token %}
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Remover</button>
    </form>
    <a href="{%url 'loja:index'%}">Voltar</a>
</div>
{% endblock %}

sistemavendas/sitevendas/loja/templates/loja/loja.html
{% extends "loja/base_loja.html" %}
{% block body %}
<h1>Produtos</h1>
<ul>
    {%for product in list_product%}
        <li>
           {{ product.name }}
                {% if perfil %}
                    {%if product.id in itens_order%}
                        <a href="{%url 'loja:remove_item' product.id order.id%}">Remover</a>
                    {%else%}
                        <a href="{%url 'loja:add_item' product.id order.id%}">Adicionar</a>
                    {%endif%}
                {% endif %}
         </li>
    {% endfor %}
</ul>
{% endblock %}

sistemavendas/sitevendas/loja/templates/loja/order.html
{% extends "loja/base_loja.html" %}
{% block body %}
<h1>Pedidos</h1>
{%for order in list_order%}
    <ul>
       <li>
           <p>{{order}}</p>
           <p>Status: {{order.get_status_order_display}}</p>
           {%if 'P.A' in order.status_order%}
           <form class="form-signin" action="{% url 'loja:list_order' perfil.id%}" method="post">
                {% csrf_token %}
                <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Finalizar</button>
            </form>
           {%endif%}
        </li>
    </ul>
{%endfor%}

<a href="{%url 'loja:index'%}">Voltar</a>
{% endblock %}