sistemavendas/sitevendas/loja/urls.py
from django.urls import path
from . import views

app_name = 'loja'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:product_id>/<int:order_id>/add', views.AddView.as_view(), name="add_item"),
    path('<int:product_id>/<int:order_id>/remove', views.RemoveView.as_view(), name='remove_item'),
    path('<int:perfil_id>/order', views.OrderView.as_view(), name='list_order')
]

sistemavendas/sitevendas/sitevendas/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('usuario/', include('usuarios.urls')),
    path('', include('loja.urls')),
    path('loja/', include('loja.urls')),
    path('admin/', admin.site.urls),
]

sistemavendas/sitevendas/usuarios/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'usuarios'
urlpatterns = [
    path('registrar/', views.RegisterView.as_view(), name='registrar'),
    path('login/',  auth_views.LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

sistemavendas/sitevendas/usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

class Perfil(models.Model):
    nome = models.CharField(max_length=255, null=False)
    telefone = models.CharField(max_length=15, null=False)
    
    @property
    def email(self):
        return self.usuario.email
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, related_name="perfil")


    def __str__(self):
        return str({}).format(self.nome)

sistemavendas/sitevendas/usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class RegisterForm(forms.Form):
    nome = forms.CharField(required=True)       
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(RegisterForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')
            valid = False
        user_exists = User.objects.filter(email=self.data['email']).exists()
        if user_exists:
            self.adiciona_erro('Usuario já existe')
            valid = False
        return valid
    
    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

sistemavendas/sitevendas/usuarios/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.models import User
from usuarios.models import Perfil
from usuarios.forms import RegisterForm
from django.contrib.auth.decorators import login_required

@login_required
def get_perfil_logado(request):
     return request.user.perfil

class RegisterView(View):
    template_name = 'usuarios/registrar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            dados_form = form.data
            usuario = User.objects.create_user(dados_form['email'], dados_form['email'], dados_form['senha'])            
            perfil = Perfil(nome=dados_form['nome'],
                            telefone=dados_form['telefone'],
                            usuario=usuario)
            perfil.save()
            return redirect('loja:index')
        return render(request, self.template_name, {'form' : form})

sistemavendas/sitevendas/usuarios/templates/usuarios/base_usuario.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>Vendas</title>
        <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "styles/main.css" %}" rel="stylesheet">
    </head>
    <body>
        <div class="container">
            {% block body %}

            {% endblock %} 
        </div>
    </body>
</html>

sistemavendas/sitevendas/usuarios/templates/usuarios/login.html
{% extends "usuarios/base_usuario.html" %}

{% block body %}

    <form class="form-signin" role="form" action="{% url 'usuarios:login' %}" method="post">
        {% csrf_token %}

        <h2 class="form-signin-heading">Login</h2>

        <input type="text" id="id_username" name="username" class="form-control" placeholder="Email" required autofocus>

        <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

        <input type="hidden" name="next" value="{{ next }}" />

        {% if form.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Por favor, verifique o Email e/ou Senha informados
          </div>
        {% endif %}
        <a href="{% url 'usuarios:registrar' %}">registre-se</a>
    </form>

{% endblock %}

sistemavendas/sitevendas/usuarios/templates/usuarios/registrar.html
<!-- connectedin/usuarios/templates/registrar.html -->

{% extends "usuarios/base_usuario.html" %}

{% block body %}

  <form class="form-signin" action="{% url 'usuarios:registrar' %}" method="post">
    {% csrf_token %}
    <h2 class="form-signin-heading">Crie seu usuário</h2>

    <input type="text" id="id_email" name="email" class="form-control" placeholder="Email *" required autofocus>

    <input type="text" id="id_nome" name="nome" class="form-control" placeholder="Nome *" required >

    <input type="password" id="id_senha" name="senha" class="form-control" placeholder="Senha *" required>

    <hr />

    <input type="text" id="id_telefone" name="telefone" class="form-control" placeholder="Telefone">

    <hr />

    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>

    <hr/>

    {% if form.errors %}
     <div class="alert alert-danger">
       <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
       {{form.non_field_errors}}
     </div>
   {% endif %}

  </form>

{% endblock %}